# Generated by Django 4.2.30 on 2026-05-21 11:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commercant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('nom', models.CharField(max_length=100)),
                ('telephone', models.CharField(max_length=20, unique=True)),
                ('ville', models.CharField(default='Comé', max_length=100)),
                ('pin_hash', models.CharField(blank=True, max_length=128)),
                ('date_inscription', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Commerçante',
                'verbose_name_plural': 'Commerçantes',
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('telephone', models.CharField(blank=True, max_length=20)),
                ('limite_credit', models.PositiveIntegerField(default=50000)),
                ('commercant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clients', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Fournisseur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('telephone', models.CharField(blank=True, max_length=20)),
                ('commercant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fournisseurs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LotAchat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite_sacs', models.PositiveIntegerField()),
                ('prix_achat_sac', models.PositiveIntegerField()),
                ('prix_vente_sac', models.PositiveIntegerField()),
                ('duree_ecoulement_jours', models.PositiveIntegerField(default=5)),
                ('date_achat', models.DateField(default=django.utils.timezone.now)),
                ('mode_paiement', models.CharField(choices=[('comptant', 'Comptant'), ('credit', 'Crédit')], default='credit', max_length=10)),
                ('quantite_restante', models.PositiveIntegerField()),
                ('commercant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lots', to=settings.AUTH_USER_MODEL)),
                ('fournisseur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lots', to='api.fournisseur')),
            ],
        ),
        migrations.CreateModel(
            name='Vente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unite', models.CharField(choices=[('sac', '1 sac'), ('demi_sac', '½ sac'), ('quart_sac', '¼ sac'), ('sachet_bleu', 'Sachet bleu'), ('sachet_jaune', 'Sachet jaune'), ('bols', 'Bols (kg)')], max_length=15)),
                ('quantite', models.DecimalField(decimal_places=2, max_digits=6)),
                ('prix_unitaire', models.PositiveIntegerField()),
                ('montant_total', models.PositiveIntegerField()),
                ('mode_paiement', models.CharField(choices=[('comptant', 'Comptant'), ('credit', 'Crédit'), ('mixte', 'Mixte')], default='comptant', max_length=10)),
                ('montant_rembourse', models.PositiveIntegerField(default=0)),
                ('date_vente', models.DateTimeField(default=django.utils.timezone.now)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ventes', to='api.client')),
                ('commercant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ventes', to=settings.AUTH_USER_MODEL)),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ventes', to='api.lotachat')),
            ],
        ),
        migrations.CreateModel(
            name='Remboursement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.PositiveIntegerField()),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='remboursements', to='api.client')),
                ('commercant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='remboursements', to=settings.AUTH_USER_MODEL)),
                ('vente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='remboursements', to='api.vente')),
            ],
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(choices=[('mais', 'Maïs'), ('soja', 'Soja'), ('mil', 'Mil')], max_length=10)),
                ('commercant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('nom', 'commercant')},
            },
        ),
        migrations.CreateModel(
            name='PaiementFournisseur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.PositiveIntegerField()),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('commercant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paiements_fournisseur', to=settings.AUTH_USER_MODEL)),
                ('fournisseur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paiements', to='api.fournisseur')),
            ],
        ),
        migrations.AddField(
            model_name='lotachat',
            name='produit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lots', to='api.produit'),
        ),
        migrations.CreateModel(
            name='ConfigMarche',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cycle_jours', models.PositiveIntegerField(default=5)),
                ('date_reference', models.DateField()),
                ('fournisseur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='configs_marche', to='api.fournisseur')),
            ],
        ),
    ]
