# Generated by Django 4.2.30 on 2026-05-21 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_otpcode_alter_lotachat_date_achat'),
    ]

    operations = [
        migrations.AddField(
            model_name='vente',
            name='date_echeance',
            field=models.DateField(blank=True, null=True),
        ),
    ]
