# Generated by Django 4.2.30 on 2026-05-21 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_vente_date_echeance'),
    ]

    operations = [
        migrations.AddField(
            model_name='configmarche',
            name='delai_remboursement_jours',
            field=models.PositiveIntegerField(default=30),
        ),
        migrations.AddField(
            model_name='configmarche',
            name='montant_minimum_marche',
            field=models.PositiveIntegerField(default=150000),
        ),
    ]
